=== mogobiz/mogopay-core/doc/sips/apiServer_206/server/access/accessList.dtd
<!ELEMENT list (accept, deny)>
<!ELEMENT accept (acceptList*, acceptAddress*)>
	<!ELEMENT acceptList (#PCDATA)>
		<!ATTLIST acceptList
			from CDATA #REQUIRED
			to CDATA #REQUIRED
		>
	<!ELEMENT acceptAddress (#PCDATA)>

<!ELEMENT deny (denyList*, denyAddress*)>
	<!ELEMENT denyList (#PCDATA)>
		<!ATTLIST denyList
			from CDATA #REQUIRED
			to CDATA #REQUIRED
		>
	<!ELEMENT denyAddress (#PCDATA)>

=== mogobiz/mogopay-core/doc/sips/apiServer_206/server/access/accessListService.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "accessList.dtd">
<list>
	<accept>
		<acceptList from="1.1.1.1" to="1.1.1.20" />
		<acceptList from="1.1.2.1" to="1.1.2.11" />
		<acceptAddress>4.4.4.4</acceptAddress>
		<acceptAddress>5.5.5.5</acceptAddress>
	</accept>
	<deny>
		<denyList from="1.1.1.3" to="1.1.1.10" />
		<denyList from="2.2.2.3" to="2.2.2.11" />
		<denyAddress>8.8.8.8</denyAddress>
		<denyAddress>8.8.8.9</denyAddress>
	</deny>
</list>
