=== mogobiz/mogopay-core/doc/sips/apiServer_206/server/config/config.dtd
<!ELEMENT configuration (service, command, httpRequest, watchdog,documentRoot, routing, alert, components?)>
<!ELEMENT service (servicePort, maxServiceRequest, queueSizeMaxService, accessListService)>
	<!ELEMENT servicePort (#PCDATA)>
	<!ELEMENT maxServiceRequest (#PCDATA)>
	<!ELEMENT queueSizeMaxService (#PCDATA)>
	<!ELEMENT accessListService (#PCDATA)>
<!ELEMENT command (commandPort, maxCommandRequest, queueSizeMaxCommand, accessListCommand)>
	<!ELEMENT commandPort (#PCDATA)>
	<!ELEMENT maxCommandRequest (#PCDATA)>
	<!ELEMENT queueSizeMaxCommand (#PCDATA)>
	<!ELEMENT accessListCommand (#PCDATA)>
<!ELEMENT httpRequest (httpRequestPort, maxHttpRequest, queueSizeMaxHttpRequest, accessListHttpRequest)>
	<!ELEMENT httpRequestPort (#PCDATA)>
	<!ELEMENT maxHttpRequest (#PCDATA)>
	<!ELEMENT queueSizeMaxHttpRequest (#PCDATA)>
	<!ELEMENT accessListHttpRequest (#PCDATA)>
<!ELEMENT watchdog (pollingTimer, survPort, trace, alternateTrace+)>
	<!ELEMENT pollingTimer (#PCDATA)>
	<!ELEMENT survPort (#PCDATA)>
	<!ELEMENT trace (#PCDATA)>
		<!ATTLIST trace
			level CDATA #REQUIRED
			sizeLimit CDATA #REQUIRED
			unit CDATA #REQUIRED
			path CDATA #REQUIRED
			prefix CDATA #REQUIRED
		>
	<!ELEMENT alternateTrace (#PCDATA)>
		<!ATTLIST alternateTrace
			id CDATA #REQUIRED
			path CDATA #REQUIRED
			prefix CDATA #REQUIRED
		>
<!ELEMENT documentRoot (#PCDATA)>		
<!ELEMENT routing (componentDir)>
	<!ELEMENT componentDir (#PCDATA)>
<!ELEMENT alert (alertURL, alertProxyHost?, alertProxyPort?)>
	<!ELEMENT alertURL (#PCDATA)>	
	<!ELEMENT alertProxyHost (#PCDATA)>
	<!ELEMENT alertProxyPort (#PCDATA)>
<!ELEMENT components (pathfile+)>
	<!ELEMENT pathfile (#PCDATA)>
		<!ATTLIST pathfile
			id CDATA #REQUIRED
			path CDATA #REQUIRED
		>

=== mogobiz/mogopay-core/doc/sips/apiServer_206/server/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "config.dtd">
<configuration>
	<service>
		<servicePort>7180</servicePort>
		<maxServiceRequest>5</maxServiceRequest>
		<queueSizeMaxService>5</queueSizeMaxService>
		<accessListService>chemin_du_fichier_accessListService.xml</accessListService>
	</service>
	<command>
		<commandPort>7181</commandPort>
		<maxCommandRequest>5</maxCommandRequest>
		<queueSizeMaxCommand>5</queueSizeMaxCommand>
		<accessListCommand>chemin_du_fichier_accessListCommand.xml</accessListCommand>
	</command>
	<httpRequest>
		<httpRequestPort>7182</httpRequestPort>
		<maxHttpRequest>1</maxHttpRequest>
		<queueSizeMaxHttpRequest>1</queueSizeMaxHttpRequest>
		<accessListHttpRequest>chemin_du_fichier_accessListHttpRequest.xml</accessListHttpRequest>
	</httpRequest>
	<watchdog>
		<pollingTimer>6000</pollingTimer>
		<survPort>7183</survPort>
		<trace level="0" sizeLimit="1000" unit="Line" path="chemin_du_repertoire_de_traces" prefix="APIServer" />
<!--		<alternateTrace id="example" path="chemin_du_repertoire_de_traces" prefix="example" />	-->
		<alternateTrace id="" path="./" prefix="" />
	</watchdog>
	<documentRoot>chemin_du_repertoire_HttpRoot</documentRoot>
	<routing>
		<componentDir>chemin_du_repertoire_components</componentDir>
	</routing>
	<alert>
		<alertURL></alertURL>
		<alertProxyHost></alertProxyHost>
		<alertProxyPort></alertProxyPort>
	</alert>
	<components>
		<pathfile id="example" path="chemin_du_fichier_pathfile" />
	</components>
</configuration>
